# See http://www.appveyor.com/docs/appveyor-yml for many more options

version: 0.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  except:
  - gh-pages

skip_tags: true

image:
- Visual Studio 2017
- Ubuntu

for:
- matrix:
    only:
    - PowerShell: 6
      image: Visual Studio 2017
  cache:
  - '%USERPROFILE%\Documents\PowerShell\Modules -> requirements.psd1'
  - '%APPDATA%\npm'
  - '%APPDATA%\npm-cache'
  - '%LOCALAPPDATA%\pip\cache -> requirements.txt'
  - 'C:\Python27\Lib\site-packages -> requirements.txt'
  - 'C:\Python27\Scripts\mkdocs.exe -> requirements.txt'
  build_script:
  - pwsh: ./build/build.ps1 -DeploymentMode
- matrix:
    only:
    - PowerShell: 6
      image: Ubuntu
  cache:
  - '$HOME/.local/share/powershell/Modules -> requirements.psd1'
  - '$HOME/.nvm'
  - '$HOME/.npm'
  - '$HOME/.cache/pip -> requirements.txt'
  - '$HOME/.local/lib/python2.7/site-packages -> requirements.txt'
  - '$HOME/.local/bin/mkdocs -> requirements.txt'
  build_script:
  - pwsh: ./build/build.ps1
- matrix:
    only:
    - PowerShell: 5
  cache:
  - '%USERPROFILE%\Documents\WindowsPowerShell\Modules -> requirements.psd1'
  - '%APPDATA%\npm'
  - '%APPDATA%\npm-cache'
  - '%LOCALAPPDATA%\pip\cache -> requirements.txt'
  - 'C:\Python27\Lib\site-packages -> requirements.txt'
  - 'C:\Python27\Scripts\mkdocs.exe -> requirements.txt'
  build_script:
  - ps: ./build/build.ps1
- matrix:
    only:
    - PowerShell: 6
  cache:
  - '%USERPROFILE%\Documents\PowerShell\Modules -> requirements.psd1'
  - '%APPDATA%\npm'
  - '%APPDATA%\npm-cache'
  - '%LOCALAPPDATA%\pip\cache -> requirements.txt'
  - 'C:\Python27\Lib\site-packages -> requirements.txt'
  - 'C:\Python27\Scripts\mkdocs.exe -> requirements.txt'
  build_script:
  - pwsh: ./build/build.ps1

matrix:
  exclude:
  - PowerShell: 5
    image: Ubuntu

clone_depth: 50

environment:
  NUGET_API_KEY:
    secure: u2jbw68/5JWUmA5z8fBok8TNO0BAJ41CSNGUJeVAtrIgDJ7p7TqW6dTbFmytP9UG
  matrix:
  - PowerShell: 5
  - PowerShell: 6

test: off

deploy: off
