# See http://www.appveyor.com/docs/appveyor-yml for many more options

version: 0.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  except:
  - gh-pages

skip_tags: true

image: Visual Studio 2017

for:
- matrix:
    only:
    - PowerShell: 6
  build_script:
  - pwsh: ./build.ps1
- matrix:
    only:
    - PowerShell: 5
  build_script:
  - ps: ./build.ps1
  # - ps: . .\build.ps1 -Task 'Deploy'

clone_depth: 50

environment:
  NUGET_API_KEY:
    secure: u2jbw68/5JWUmA5z8fBok8TNO0BAJ41CSNGUJeVAtrIgDJ7p7TqW6dTbFmytP9UG
  matrix:
  - PowerShell: 5
  - PowerShell: 6

# nuget:
#   project_feed: true

test: off

deploy: off
